# name=input("Enter your name: ")
# age=int(input("Enter your age: "))
# print('你好, ' + name)
# print('你明年', age + 1, ' 岁')
# print(type(name))
# print(type(age))
# a = int("25")
# b = float("25.6")
# #c = int("25.6")
name=input("Enter your name: ")
age=int(input("Enter your age: "))
height=float(input("Enter your height(单位:  米): "))
print('你好, ' + name)
print('你今年', age , ' 岁')
print('你的身高是', height, '米')
print(f'你好,{name}, 你今年{age}岁, 你的身高是{height}米')
print(type(name))
print(type(age))
print(type(height))
